---
layout: single
title: 06-1 예외 처리
categories: Python
tag: [python, blog]
toc: true
---

# 오류의 종류
- 프로그램 실행 전에 발생하는 오류 : 구문 오류(Synax Error)
- 프로그램 실행 중에 발생하는 오류 : 예외(exception) 또는 런타임 오류(runtime error)

### - 구문 오류
- 괄호의 개수, 들여쓰기 문제 등으로 프로그램이 실행 하기전 발생하는 오류.

```python
print("안녕하세요!) 
# 닫는 따옴표가 미표기로 구문 오류 발생.
# 해결법 : 닫는 따옴표를 표기하여 구문 오류 해결
```

### - 예외

```python
# 프로그램 시작
print("# 프로그램이 시작되었습니다!")
# 예외 발생 코드
list_a[1]
# list_a를 읽을때 NameError 오류 발생.
# 해결 예
list_a = [1, 2, 3, 4, 5]
list_a[1]
```

## 기본 예외 처리
- 예외를 처리하는 방법은 try 구문을 사용하거나 조건문을 사용함.

### - 조건문으로 예외 처리하기
- 정수를 입력하지 않았을 때를 조건.
- 문자열의 isdigit() 함수를 사용해서 숫자로만 구성된 글자인지 확인.
- 이렇게 하면 int() 함수를 이용하여 숫자로 변환할 수 없는 문자열을 변환하면서 발생하는 예외를 피할 수 있음.

## try except 구문
- 프로그램이 강제로 죽어버리는 상황을 막기 위한 것.

```python
try:
	예외가 발생할 가능성이 있는 코드
except:
	예외가 발생했을 때 실행할 코드
```

### - try except 구문과 pass 키워드 조합하기

```python
try:
	예외가 발생할 가능성이 있는 코드
except:
	예외가 발생했을 때 실행할 코드
	pass
```

### - try except else 구문

```python
try:
	예외가 발생할 가능성이 있는 코드
except:
	예외가 발생했을 때 실행할 코드
else:
	예외가 발생하지 않았을 때 실행할 코드
```

## finally 구문
- finally 구문은 가장 마지막에 사용할 수 있는 구문

```python
try:
	예외가 발생할 가능성이 있는 코드
except:
	예외가 발생했을 때 실행할 코드
else:
	예외가 발생하지 않았을 때 실행할 코드
finally:
	무조건 실행할 코드
```

### - try, except, finally 구문 조합
- try 구문은 단독 사용 x, 반드시 except 구문 또는 finally 구문과 함께 사용
- else 구문은 반드시 except 구문 뒤에 와야 함.
- 예) try + except, try + except + else, try + except + finally, try + except + else + finally, try + finally 

### - closed 속성 : 제대로 파일이 닫혀있는지 확인

### - try 구문 내부에서 return 키워드 사용 가능

### - 반복문과 함께 사용하는 경우
